# version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: shashwat123
      POSTGRES_PASSWORD: Bajpai@123
      POSTGRES_DB: AI-backend
    ports:
      - "5432:5432"

  server:
    container_name: server_container
    build: .
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    entrypoint: [ "/app/entrypoint.sh" ]
    dns:
      - 8.8.8.8
      - 1.1.1.1