# version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: shashwat123
      POSTGRES_PASSWORD: Bajpai@123
      POSTGRES_DB: AI-backend
    ports:
      - "5432:5432"